FROM maven:3.9.4-eclipse-temurin-20 as build
WORKDIR /helidon
ADD pom.xml .
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip
ADD src src
RUN mvn package -DskipTests
RUN echo "done! - build stage"

FROM busybox as download
WORKDIR /var/cache
RUN wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.27.0/opentelemetry-javaagent.jar
RUN echo "done! - download stage"

FROM eclipse-temurin:20-jdk
WORKDIR /helidon
COPY --from=build /helidon/target/k8s-helidon-app.jar ./
COPY --from=build /helidon/target/libs ./libs
COPY --from=download /var/cache ./agent

ARG OTEL_TRACES_EXPORTER=otlp
ARG OTEL_SERVICE_NAME=k8s-helidon-app-otel
ARG OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
ARG OTEL_EXPORTER_OTLP_TRACES_HEADERS
ARG OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
# ARG OTEL_METRICS_EXPORTER=otlp
# ARG OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
# ARG OTEL_EXPORTER_OTLP_METRICS_HEADERS
# ARG OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf

ENV OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
ENV OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
ENV OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=${OTEL_EXPORTER_OTLP_TRACES_PROTOCOL}
ENV OTEL_EXPORTER_OTLP_TRACES_HEADERS=${OTEL_EXPORTER_OTLP_TRACES_HEADERS}
ENV OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
# ENV OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
# ENV OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}
# ENV OTEL_EXPORTER_OTLP_METRICS_HEADERS=${OTEL_EXPORTER_OTLP_METRICS_HEADERS}
# ENV OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=${OTEL_EXPORTER_OTLP_METRICS_PROTOCOL}

CMD ["java", "--enable-preview", "-javaagent:/helidon/agent/opentelemetry-javaagent.jar","-jar", "k8s-helidon-app.jar"]
EXPOSE 8080
