{
 "title": "Helidon Metrics Endpoint Monitoring",
 "description": "Helidon Metrics Endpoint Monitoring",
 "tags": [
  "microprofile",
  "helidon",
  "jvm"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PodName",
    "label": "podName",
    "query": {
     "query": "label_values(vendor_requests_count_total, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{pod=~\"$PodName\"}",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Total",
   "type": "graph",
   "description": "base_gc_total_total Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{pod=~\"$PodName\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Time",
   "type": "graph",
   "description": "base_gc_time_total Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The JVM implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_seconds{pod=~\"$PodName\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{pod=~\"$PodName\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{pod=~\"$PodName\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{pod=~\"$PodName\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Currently loaded Classes",
   "type": "stat",
   "description": "base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Total loaded Classes",
   "type": "stat",
   "description": "base_classloader_loadedClasses_total_total Displays the total number of classes that have been loaded since the JVM has started execution.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total{pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Total unloaded Classes",
   "type": "stat",
   "description": "base_classloader_unloadedClasses_total_total Displays the total number of classes unloaded since the JVM has started execution.",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total{pod=~\"$PodName\"}"
    }
   ]
  }
 ]
}