apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-helidon-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    hosts:
      - helidon.shukawam.me
    secretName: shukawam-tls-secret
  rules:
    - host: helidon.shukawam.me
      http:
        paths:
          - backend:
              service:
                name: k8s-helidon-app
                port:
                  number: 8080
            path: /
            pathType: Prefix
