apiVersion: v1
kind: Service
metadata:
  name: k8s-helidon-app
  labels:
    app: k8s-helidon-app
spec:
  type: ClusterIP
  selector:
    app: k8s-helidon-app
  ports:
    - port: 80
      targetPort: 8080
      name: http
