name: Build k8s-helidon-app-otel

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Format chack
        run: |
          mvn formatter:validate

      - name: Test with Maven
        run: |
          mvn test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.otel
          build-args:
            OTEL_EXPORTER_OTLP_TRACES_HEADERS=${{ secrets.OTEL_EXPORTER_OTLP_TRACES_HEADERS }}
            OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}
          tags: |
            ${{ env.IMAGE }}:latest
        env:
          IMAGE: ghcr.io/${{ github.repository }}-otel
