name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"
          cache: maven

      - name: Format chack
        run: |
          mvn formatter:validate

      - name: Test with Maven
        run: |
          mvn test

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
        env:
          IMAGE: ghcr.io/${{ github.repository }}
